// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package twitter.simplified.clone.domain;

import org.springframework.beans.factory.annotation.Configurable;
import twitter.simplified.clone.domain.FollowDataOnDemand;

privileged aspect FollowDataOnDemand_Roo_Configurable {
    
    declare @type: FollowDataOnDemand: @Configurable;
    
}
